/*
H3Net Protocol API

H3Net Protocol schema with various messages and configurations.

API version: 1.0.0
Contact: h3netprotocol@googlegroups.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package h3netclient

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the CreateFlowRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateFlowRequest{}

// CreateFlowRequest struct for CreateFlowRequest
type CreateFlowRequest struct {
	Type string `json:"type"`
	Timestamp time.Time `json:"timestamp"`
	// Client-generated request ID for tracking
	RequestId string `json:"requestId"`
	// Device identifier
	DeviceId string `json:"deviceId"`
	// Table identifier
	TableId int32 `json:"tableId"`
	// Flow entry priority, higher values take precedence
	Priority int32 `json:"priority"`
	Match FlowMatch `json:"match"`
	Actions FlowAction `json:"actions"`
	// Identifier of the next table to evaluate if this entry matches
	NextTable *int32 `json:"nextTable,omitempty"`
	// Count of packets matched by this flow entry
	PacketCounter *int32 `json:"packetCounter,omitempty"`
	// Total bytes matched by this flow entry
	ByteCounter *int32 `json:"byteCounter,omitempty"`
}

type _CreateFlowRequest CreateFlowRequest

// NewCreateFlowRequest instantiates a new CreateFlowRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateFlowRequest(type_ string, timestamp time.Time, requestId string, deviceId string, tableId int32, priority int32, match FlowMatch, actions FlowAction) *CreateFlowRequest {
	this := CreateFlowRequest{}
	this.Type = type_
	this.Timestamp = timestamp
	this.RequestId = requestId
	this.DeviceId = deviceId
	this.TableId = tableId
	this.Priority = priority
	this.Match = match
	this.Actions = actions
	return &this
}

// NewCreateFlowRequestWithDefaults instantiates a new CreateFlowRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateFlowRequestWithDefaults() *CreateFlowRequest {
	this := CreateFlowRequest{}
	return &this
}

// GetType returns the Type field value
func (o *CreateFlowRequest) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CreateFlowRequest) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CreateFlowRequest) SetType(v string) {
	o.Type = v
}

// GetTimestamp returns the Timestamp field value
func (o *CreateFlowRequest) GetTimestamp() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *CreateFlowRequest) GetTimestampOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *CreateFlowRequest) SetTimestamp(v time.Time) {
	o.Timestamp = v
}

// GetRequestId returns the RequestId field value
func (o *CreateFlowRequest) GetRequestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value
// and a boolean to check if the value has been set.
func (o *CreateFlowRequest) GetRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestId, true
}

// SetRequestId sets field value
func (o *CreateFlowRequest) SetRequestId(v string) {
	o.RequestId = v
}

// GetDeviceId returns the DeviceId field value
func (o *CreateFlowRequest) GetDeviceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeviceId
}

// GetDeviceIdOk returns a tuple with the DeviceId field value
// and a boolean to check if the value has been set.
func (o *CreateFlowRequest) GetDeviceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeviceId, true
}

// SetDeviceId sets field value
func (o *CreateFlowRequest) SetDeviceId(v string) {
	o.DeviceId = v
}

// GetTableId returns the TableId field value
func (o *CreateFlowRequest) GetTableId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TableId
}

// GetTableIdOk returns a tuple with the TableId field value
// and a boolean to check if the value has been set.
func (o *CreateFlowRequest) GetTableIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TableId, true
}

// SetTableId sets field value
func (o *CreateFlowRequest) SetTableId(v int32) {
	o.TableId = v
}

// GetPriority returns the Priority field value
func (o *CreateFlowRequest) GetPriority() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value
// and a boolean to check if the value has been set.
func (o *CreateFlowRequest) GetPriorityOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Priority, true
}

// SetPriority sets field value
func (o *CreateFlowRequest) SetPriority(v int32) {
	o.Priority = v
}

// GetMatch returns the Match field value
func (o *CreateFlowRequest) GetMatch() FlowMatch {
	if o == nil {
		var ret FlowMatch
		return ret
	}

	return o.Match
}

// GetMatchOk returns a tuple with the Match field value
// and a boolean to check if the value has been set.
func (o *CreateFlowRequest) GetMatchOk() (*FlowMatch, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Match, true
}

// SetMatch sets field value
func (o *CreateFlowRequest) SetMatch(v FlowMatch) {
	o.Match = v
}

// GetActions returns the Actions field value
func (o *CreateFlowRequest) GetActions() FlowAction {
	if o == nil {
		var ret FlowAction
		return ret
	}

	return o.Actions
}

// GetActionsOk returns a tuple with the Actions field value
// and a boolean to check if the value has been set.
func (o *CreateFlowRequest) GetActionsOk() (*FlowAction, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Actions, true
}

// SetActions sets field value
func (o *CreateFlowRequest) SetActions(v FlowAction) {
	o.Actions = v
}

// GetNextTable returns the NextTable field value if set, zero value otherwise.
func (o *CreateFlowRequest) GetNextTable() int32 {
	if o == nil || IsNil(o.NextTable) {
		var ret int32
		return ret
	}
	return *o.NextTable
}

// GetNextTableOk returns a tuple with the NextTable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateFlowRequest) GetNextTableOk() (*int32, bool) {
	if o == nil || IsNil(o.NextTable) {
		return nil, false
	}
	return o.NextTable, true
}

// HasNextTable returns a boolean if a field has been set.
func (o *CreateFlowRequest) HasNextTable() bool {
	if o != nil && !IsNil(o.NextTable) {
		return true
	}

	return false
}

// SetNextTable gets a reference to the given int32 and assigns it to the NextTable field.
func (o *CreateFlowRequest) SetNextTable(v int32) {
	o.NextTable = &v
}

// GetPacketCounter returns the PacketCounter field value if set, zero value otherwise.
func (o *CreateFlowRequest) GetPacketCounter() int32 {
	if o == nil || IsNil(o.PacketCounter) {
		var ret int32
		return ret
	}
	return *o.PacketCounter
}

// GetPacketCounterOk returns a tuple with the PacketCounter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateFlowRequest) GetPacketCounterOk() (*int32, bool) {
	if o == nil || IsNil(o.PacketCounter) {
		return nil, false
	}
	return o.PacketCounter, true
}

// HasPacketCounter returns a boolean if a field has been set.
func (o *CreateFlowRequest) HasPacketCounter() bool {
	if o != nil && !IsNil(o.PacketCounter) {
		return true
	}

	return false
}

// SetPacketCounter gets a reference to the given int32 and assigns it to the PacketCounter field.
func (o *CreateFlowRequest) SetPacketCounter(v int32) {
	o.PacketCounter = &v
}

// GetByteCounter returns the ByteCounter field value if set, zero value otherwise.
func (o *CreateFlowRequest) GetByteCounter() int32 {
	if o == nil || IsNil(o.ByteCounter) {
		var ret int32
		return ret
	}
	return *o.ByteCounter
}

// GetByteCounterOk returns a tuple with the ByteCounter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateFlowRequest) GetByteCounterOk() (*int32, bool) {
	if o == nil || IsNil(o.ByteCounter) {
		return nil, false
	}
	return o.ByteCounter, true
}

// HasByteCounter returns a boolean if a field has been set.
func (o *CreateFlowRequest) HasByteCounter() bool {
	if o != nil && !IsNil(o.ByteCounter) {
		return true
	}

	return false
}

// SetByteCounter gets a reference to the given int32 and assigns it to the ByteCounter field.
func (o *CreateFlowRequest) SetByteCounter(v int32) {
	o.ByteCounter = &v
}

func (o CreateFlowRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateFlowRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["timestamp"] = o.Timestamp
	toSerialize["requestId"] = o.RequestId
	toSerialize["deviceId"] = o.DeviceId
	toSerialize["tableId"] = o.TableId
	toSerialize["priority"] = o.Priority
	toSerialize["match"] = o.Match
	toSerialize["actions"] = o.Actions
	if !IsNil(o.NextTable) {
		toSerialize["nextTable"] = o.NextTable
	}
	if !IsNil(o.PacketCounter) {
		toSerialize["packetCounter"] = o.PacketCounter
	}
	if !IsNil(o.ByteCounter) {
		toSerialize["byteCounter"] = o.ByteCounter
	}
	return toSerialize, nil
}

func (o *CreateFlowRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"timestamp",
		"requestId",
		"deviceId",
		"tableId",
		"priority",
		"match",
		"actions",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateFlowRequest := _CreateFlowRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateFlowRequest)

	if err != nil {
		return err
	}

	*o = CreateFlowRequest(varCreateFlowRequest)

	return err
}

type NullableCreateFlowRequest struct {
	value *CreateFlowRequest
	isSet bool
}

func (v NullableCreateFlowRequest) Get() *CreateFlowRequest {
	return v.value
}

func (v *NullableCreateFlowRequest) Set(val *CreateFlowRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateFlowRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateFlowRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateFlowRequest(val *CreateFlowRequest) *NullableCreateFlowRequest {
	return &NullableCreateFlowRequest{value: val, isSet: true}
}

func (v NullableCreateFlowRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateFlowRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


