/*
H3Net Protocol API

H3Net Protocol schema with various messages and configurations.

API version: 1.0.0
Contact: h3netprotocol@googlegroups.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package h3netclient

import (
	"encoding/json"
)

// checks if the VLANPorts type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VLANPorts{}

// VLANPorts struct for VLANPorts
type VLANPorts struct {
	Untagged []NetworkInterface `json:"untagged,omitempty"`
	Tagged []NetworkInterface `json:"tagged,omitempty"`
}

// NewVLANPorts instantiates a new VLANPorts object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVLANPorts() *VLANPorts {
	this := VLANPorts{}
	return &this
}

// NewVLANPortsWithDefaults instantiates a new VLANPorts object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVLANPortsWithDefaults() *VLANPorts {
	this := VLANPorts{}
	return &this
}

// GetUntagged returns the Untagged field value if set, zero value otherwise.
func (o *VLANPorts) GetUntagged() []NetworkInterface {
	if o == nil || IsNil(o.Untagged) {
		var ret []NetworkInterface
		return ret
	}
	return o.Untagged
}

// GetUntaggedOk returns a tuple with the Untagged field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VLANPorts) GetUntaggedOk() ([]NetworkInterface, bool) {
	if o == nil || IsNil(o.Untagged) {
		return nil, false
	}
	return o.Untagged, true
}

// HasUntagged returns a boolean if a field has been set.
func (o *VLANPorts) HasUntagged() bool {
	if o != nil && !IsNil(o.Untagged) {
		return true
	}

	return false
}

// SetUntagged gets a reference to the given []NetworkInterface and assigns it to the Untagged field.
func (o *VLANPorts) SetUntagged(v []NetworkInterface) {
	o.Untagged = v
}

// GetTagged returns the Tagged field value if set, zero value otherwise.
func (o *VLANPorts) GetTagged() []NetworkInterface {
	if o == nil || IsNil(o.Tagged) {
		var ret []NetworkInterface
		return ret
	}
	return o.Tagged
}

// GetTaggedOk returns a tuple with the Tagged field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VLANPorts) GetTaggedOk() ([]NetworkInterface, bool) {
	if o == nil || IsNil(o.Tagged) {
		return nil, false
	}
	return o.Tagged, true
}

// HasTagged returns a boolean if a field has been set.
func (o *VLANPorts) HasTagged() bool {
	if o != nil && !IsNil(o.Tagged) {
		return true
	}

	return false
}

// SetTagged gets a reference to the given []NetworkInterface and assigns it to the Tagged field.
func (o *VLANPorts) SetTagged(v []NetworkInterface) {
	o.Tagged = v
}

func (o VLANPorts) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VLANPorts) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Untagged) {
		toSerialize["untagged"] = o.Untagged
	}
	if !IsNil(o.Tagged) {
		toSerialize["tagged"] = o.Tagged
	}
	return toSerialize, nil
}

type NullableVLANPorts struct {
	value *VLANPorts
	isSet bool
}

func (v NullableVLANPorts) Get() *VLANPorts {
	return v.value
}

func (v *NullableVLANPorts) Set(val *VLANPorts) {
	v.value = val
	v.isSet = true
}

func (v NullableVLANPorts) IsSet() bool {
	return v.isSet
}

func (v *NullableVLANPorts) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVLANPorts(val *VLANPorts) *NullableVLANPorts {
	return &NullableVLANPorts{value: val, isSet: true}
}

func (v NullableVLANPorts) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVLANPorts) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


