/*
H3Net Protocol API

H3Net Protocol schema with various messages and configurations.

API version: 1.0.0
Contact: h3netprotocol@googlegroups.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package h3netclient

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the DeviceConfigUpdateMessage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeviceConfigUpdateMessage{}

// DeviceConfigUpdateMessage struct for DeviceConfigUpdateMessage
type DeviceConfigUpdateMessage struct {
	Type string `json:"type"`
	// ISO 8601 formatted timestamp with timezone
	Timestamp time.Time `json:"timestamp"`
	// Schema version
	SchemaVersion string `json:"schemaVersion"`
	Device Device `json:"device"`
	Config DeviceConfigUpdateMessageAllOfConfig `json:"config"`
	ApplyImmediately *bool `json:"applyImmediately,omitempty"`
}

type _DeviceConfigUpdateMessage DeviceConfigUpdateMessage

// NewDeviceConfigUpdateMessage instantiates a new DeviceConfigUpdateMessage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeviceConfigUpdateMessage(type_ string, timestamp time.Time, schemaVersion string, device Device, config DeviceConfigUpdateMessageAllOfConfig) *DeviceConfigUpdateMessage {
	this := DeviceConfigUpdateMessage{}
	this.Type = type_
	this.Timestamp = timestamp
	this.SchemaVersion = schemaVersion
	this.Device = device
	this.Config = config
	return &this
}

// NewDeviceConfigUpdateMessageWithDefaults instantiates a new DeviceConfigUpdateMessage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeviceConfigUpdateMessageWithDefaults() *DeviceConfigUpdateMessage {
	this := DeviceConfigUpdateMessage{}
	return &this
}

// GetType returns the Type field value
func (o *DeviceConfigUpdateMessage) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *DeviceConfigUpdateMessage) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *DeviceConfigUpdateMessage) SetType(v string) {
	o.Type = v
}

// GetTimestamp returns the Timestamp field value
func (o *DeviceConfigUpdateMessage) GetTimestamp() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *DeviceConfigUpdateMessage) GetTimestampOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *DeviceConfigUpdateMessage) SetTimestamp(v time.Time) {
	o.Timestamp = v
}

// GetSchemaVersion returns the SchemaVersion field value
func (o *DeviceConfigUpdateMessage) GetSchemaVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SchemaVersion
}

// GetSchemaVersionOk returns a tuple with the SchemaVersion field value
// and a boolean to check if the value has been set.
func (o *DeviceConfigUpdateMessage) GetSchemaVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SchemaVersion, true
}

// SetSchemaVersion sets field value
func (o *DeviceConfigUpdateMessage) SetSchemaVersion(v string) {
	o.SchemaVersion = v
}

// GetDevice returns the Device field value
func (o *DeviceConfigUpdateMessage) GetDevice() Device {
	if o == nil {
		var ret Device
		return ret
	}

	return o.Device
}

// GetDeviceOk returns a tuple with the Device field value
// and a boolean to check if the value has been set.
func (o *DeviceConfigUpdateMessage) GetDeviceOk() (*Device, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Device, true
}

// SetDevice sets field value
func (o *DeviceConfigUpdateMessage) SetDevice(v Device) {
	o.Device = v
}

// GetConfig returns the Config field value
func (o *DeviceConfigUpdateMessage) GetConfig() DeviceConfigUpdateMessageAllOfConfig {
	if o == nil {
		var ret DeviceConfigUpdateMessageAllOfConfig
		return ret
	}

	return o.Config
}

// GetConfigOk returns a tuple with the Config field value
// and a boolean to check if the value has been set.
func (o *DeviceConfigUpdateMessage) GetConfigOk() (*DeviceConfigUpdateMessageAllOfConfig, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Config, true
}

// SetConfig sets field value
func (o *DeviceConfigUpdateMessage) SetConfig(v DeviceConfigUpdateMessageAllOfConfig) {
	o.Config = v
}

// GetApplyImmediately returns the ApplyImmediately field value if set, zero value otherwise.
func (o *DeviceConfigUpdateMessage) GetApplyImmediately() bool {
	if o == nil || IsNil(o.ApplyImmediately) {
		var ret bool
		return ret
	}
	return *o.ApplyImmediately
}

// GetApplyImmediatelyOk returns a tuple with the ApplyImmediately field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceConfigUpdateMessage) GetApplyImmediatelyOk() (*bool, bool) {
	if o == nil || IsNil(o.ApplyImmediately) {
		return nil, false
	}
	return o.ApplyImmediately, true
}

// HasApplyImmediately returns a boolean if a field has been set.
func (o *DeviceConfigUpdateMessage) HasApplyImmediately() bool {
	if o != nil && !IsNil(o.ApplyImmediately) {
		return true
	}

	return false
}

// SetApplyImmediately gets a reference to the given bool and assigns it to the ApplyImmediately field.
func (o *DeviceConfigUpdateMessage) SetApplyImmediately(v bool) {
	o.ApplyImmediately = &v
}

func (o DeviceConfigUpdateMessage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeviceConfigUpdateMessage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["timestamp"] = o.Timestamp
	toSerialize["schemaVersion"] = o.SchemaVersion
	toSerialize["device"] = o.Device
	toSerialize["config"] = o.Config
	if !IsNil(o.ApplyImmediately) {
		toSerialize["applyImmediately"] = o.ApplyImmediately
	}
	return toSerialize, nil
}

func (o *DeviceConfigUpdateMessage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"timestamp",
		"schemaVersion",
		"device",
		"config",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeviceConfigUpdateMessage := _DeviceConfigUpdateMessage{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeviceConfigUpdateMessage)

	if err != nil {
		return err
	}

	*o = DeviceConfigUpdateMessage(varDeviceConfigUpdateMessage)

	return err
}

type NullableDeviceConfigUpdateMessage struct {
	value *DeviceConfigUpdateMessage
	isSet bool
}

func (v NullableDeviceConfigUpdateMessage) Get() *DeviceConfigUpdateMessage {
	return v.value
}

func (v *NullableDeviceConfigUpdateMessage) Set(val *DeviceConfigUpdateMessage) {
	v.value = val
	v.isSet = true
}

func (v NullableDeviceConfigUpdateMessage) IsSet() bool {
	return v.isSet
}

func (v *NullableDeviceConfigUpdateMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeviceConfigUpdateMessage(val *DeviceConfigUpdateMessage) *NullableDeviceConfigUpdateMessage {
	return &NullableDeviceConfigUpdateMessage{value: val, isSet: true}
}

func (v NullableDeviceConfigUpdateMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeviceConfigUpdateMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


