/*
H3Net Protocol API

H3Net Protocol schema with various messages and configurations.

API version: 1.0.0
Contact: h3netprotocol@googlegroups.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package h3netclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InterfaceStats type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InterfaceStats{}

// InterfaceStats struct for InterfaceStats
type InterfaceStats struct {
	// Interface name/identifier
	Name string `json:"name"`
	// Human-readable interface description
	Description *string `json:"description,omitempty"`
	// Administrative state of the interface
	Enabled bool `json:"enabled"`
	Speed *InterfaceSpeed `json:"speed,omitempty"`
	// Interface type/media
	Type *string `json:"type,omitempty"`
	// Maximum Transmission Unit in bytes
	Mtu *int32 `json:"mtu,omitempty"`
	// MAC address in format XX:XX:XX:XX:XX:XX or XX-XX-XX-XX-XX-XX
	Mac *string `json:"mac,omitempty" validate:"regexp=^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$"`
	State *InterfaceState `json:"state,omitempty"`
	AdminState *AdminState `json:"adminState,omitempty"`
	OperStatus *string `json:"operStatus,omitempty"`
	AdminStatus *string `json:"adminStatus,omitempty"`
	VlanIds []int32 `json:"vlanIds,omitempty"`
	LastFlapped *float32 `json:"lastFlapped,omitempty"`
	Counters *InterfaceCounters `json:"counters,omitempty"`
	QosStats *QoSStats `json:"qosStats,omitempty"`
	ErrorStats *ErrorStats `json:"errorStats,omitempty"`
	OpticalStats *InterfaceStatsAllOfOpticalStats `json:"opticalStats,omitempty"`
	RateStats *InterfaceStatsAllOfRateStats `json:"rateStats,omitempty"`
}

type _InterfaceStats InterfaceStats

// NewInterfaceStats instantiates a new InterfaceStats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInterfaceStats(name string, enabled bool) *InterfaceStats {
	this := InterfaceStats{}
	this.Name = name
	this.Enabled = enabled
	return &this
}

// NewInterfaceStatsWithDefaults instantiates a new InterfaceStats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInterfaceStatsWithDefaults() *InterfaceStats {
	this := InterfaceStats{}
	return &this
}

// GetName returns the Name field value
func (o *InterfaceStats) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *InterfaceStats) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *InterfaceStats) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *InterfaceStats) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InterfaceStats) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *InterfaceStats) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *InterfaceStats) SetDescription(v string) {
	o.Description = &v
}

// GetEnabled returns the Enabled field value
func (o *InterfaceStats) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *InterfaceStats) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *InterfaceStats) SetEnabled(v bool) {
	o.Enabled = v
}

// GetSpeed returns the Speed field value if set, zero value otherwise.
func (o *InterfaceStats) GetSpeed() InterfaceSpeed {
	if o == nil || IsNil(o.Speed) {
		var ret InterfaceSpeed
		return ret
	}
	return *o.Speed
}

// GetSpeedOk returns a tuple with the Speed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InterfaceStats) GetSpeedOk() (*InterfaceSpeed, bool) {
	if o == nil || IsNil(o.Speed) {
		return nil, false
	}
	return o.Speed, true
}

// HasSpeed returns a boolean if a field has been set.
func (o *InterfaceStats) HasSpeed() bool {
	if o != nil && !IsNil(o.Speed) {
		return true
	}

	return false
}

// SetSpeed gets a reference to the given InterfaceSpeed and assigns it to the Speed field.
func (o *InterfaceStats) SetSpeed(v InterfaceSpeed) {
	o.Speed = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *InterfaceStats) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InterfaceStats) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *InterfaceStats) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *InterfaceStats) SetType(v string) {
	o.Type = &v
}

// GetMtu returns the Mtu field value if set, zero value otherwise.
func (o *InterfaceStats) GetMtu() int32 {
	if o == nil || IsNil(o.Mtu) {
		var ret int32
		return ret
	}
	return *o.Mtu
}

// GetMtuOk returns a tuple with the Mtu field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InterfaceStats) GetMtuOk() (*int32, bool) {
	if o == nil || IsNil(o.Mtu) {
		return nil, false
	}
	return o.Mtu, true
}

// HasMtu returns a boolean if a field has been set.
func (o *InterfaceStats) HasMtu() bool {
	if o != nil && !IsNil(o.Mtu) {
		return true
	}

	return false
}

// SetMtu gets a reference to the given int32 and assigns it to the Mtu field.
func (o *InterfaceStats) SetMtu(v int32) {
	o.Mtu = &v
}

// GetMac returns the Mac field value if set, zero value otherwise.
func (o *InterfaceStats) GetMac() string {
	if o == nil || IsNil(o.Mac) {
		var ret string
		return ret
	}
	return *o.Mac
}

// GetMacOk returns a tuple with the Mac field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InterfaceStats) GetMacOk() (*string, bool) {
	if o == nil || IsNil(o.Mac) {
		return nil, false
	}
	return o.Mac, true
}

// HasMac returns a boolean if a field has been set.
func (o *InterfaceStats) HasMac() bool {
	if o != nil && !IsNil(o.Mac) {
		return true
	}

	return false
}

// SetMac gets a reference to the given string and assigns it to the Mac field.
func (o *InterfaceStats) SetMac(v string) {
	o.Mac = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *InterfaceStats) GetState() InterfaceState {
	if o == nil || IsNil(o.State) {
		var ret InterfaceState
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InterfaceStats) GetStateOk() (*InterfaceState, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *InterfaceStats) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given InterfaceState and assigns it to the State field.
func (o *InterfaceStats) SetState(v InterfaceState) {
	o.State = &v
}

// GetAdminState returns the AdminState field value if set, zero value otherwise.
func (o *InterfaceStats) GetAdminState() AdminState {
	if o == nil || IsNil(o.AdminState) {
		var ret AdminState
		return ret
	}
	return *o.AdminState
}

// GetAdminStateOk returns a tuple with the AdminState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InterfaceStats) GetAdminStateOk() (*AdminState, bool) {
	if o == nil || IsNil(o.AdminState) {
		return nil, false
	}
	return o.AdminState, true
}

// HasAdminState returns a boolean if a field has been set.
func (o *InterfaceStats) HasAdminState() bool {
	if o != nil && !IsNil(o.AdminState) {
		return true
	}

	return false
}

// SetAdminState gets a reference to the given AdminState and assigns it to the AdminState field.
func (o *InterfaceStats) SetAdminState(v AdminState) {
	o.AdminState = &v
}

// GetOperStatus returns the OperStatus field value if set, zero value otherwise.
func (o *InterfaceStats) GetOperStatus() string {
	if o == nil || IsNil(o.OperStatus) {
		var ret string
		return ret
	}
	return *o.OperStatus
}

// GetOperStatusOk returns a tuple with the OperStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InterfaceStats) GetOperStatusOk() (*string, bool) {
	if o == nil || IsNil(o.OperStatus) {
		return nil, false
	}
	return o.OperStatus, true
}

// HasOperStatus returns a boolean if a field has been set.
func (o *InterfaceStats) HasOperStatus() bool {
	if o != nil && !IsNil(o.OperStatus) {
		return true
	}

	return false
}

// SetOperStatus gets a reference to the given string and assigns it to the OperStatus field.
func (o *InterfaceStats) SetOperStatus(v string) {
	o.OperStatus = &v
}

// GetAdminStatus returns the AdminStatus field value if set, zero value otherwise.
func (o *InterfaceStats) GetAdminStatus() string {
	if o == nil || IsNil(o.AdminStatus) {
		var ret string
		return ret
	}
	return *o.AdminStatus
}

// GetAdminStatusOk returns a tuple with the AdminStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InterfaceStats) GetAdminStatusOk() (*string, bool) {
	if o == nil || IsNil(o.AdminStatus) {
		return nil, false
	}
	return o.AdminStatus, true
}

// HasAdminStatus returns a boolean if a field has been set.
func (o *InterfaceStats) HasAdminStatus() bool {
	if o != nil && !IsNil(o.AdminStatus) {
		return true
	}

	return false
}

// SetAdminStatus gets a reference to the given string and assigns it to the AdminStatus field.
func (o *InterfaceStats) SetAdminStatus(v string) {
	o.AdminStatus = &v
}

// GetVlanIds returns the VlanIds field value if set, zero value otherwise.
func (o *InterfaceStats) GetVlanIds() []int32 {
	if o == nil || IsNil(o.VlanIds) {
		var ret []int32
		return ret
	}
	return o.VlanIds
}

// GetVlanIdsOk returns a tuple with the VlanIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InterfaceStats) GetVlanIdsOk() ([]int32, bool) {
	if o == nil || IsNil(o.VlanIds) {
		return nil, false
	}
	return o.VlanIds, true
}

// HasVlanIds returns a boolean if a field has been set.
func (o *InterfaceStats) HasVlanIds() bool {
	if o != nil && !IsNil(o.VlanIds) {
		return true
	}

	return false
}

// SetVlanIds gets a reference to the given []int32 and assigns it to the VlanIds field.
func (o *InterfaceStats) SetVlanIds(v []int32) {
	o.VlanIds = v
}

// GetLastFlapped returns the LastFlapped field value if set, zero value otherwise.
func (o *InterfaceStats) GetLastFlapped() float32 {
	if o == nil || IsNil(o.LastFlapped) {
		var ret float32
		return ret
	}
	return *o.LastFlapped
}

// GetLastFlappedOk returns a tuple with the LastFlapped field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InterfaceStats) GetLastFlappedOk() (*float32, bool) {
	if o == nil || IsNil(o.LastFlapped) {
		return nil, false
	}
	return o.LastFlapped, true
}

// HasLastFlapped returns a boolean if a field has been set.
func (o *InterfaceStats) HasLastFlapped() bool {
	if o != nil && !IsNil(o.LastFlapped) {
		return true
	}

	return false
}

// SetLastFlapped gets a reference to the given float32 and assigns it to the LastFlapped field.
func (o *InterfaceStats) SetLastFlapped(v float32) {
	o.LastFlapped = &v
}

// GetCounters returns the Counters field value if set, zero value otherwise.
func (o *InterfaceStats) GetCounters() InterfaceCounters {
	if o == nil || IsNil(o.Counters) {
		var ret InterfaceCounters
		return ret
	}
	return *o.Counters
}

// GetCountersOk returns a tuple with the Counters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InterfaceStats) GetCountersOk() (*InterfaceCounters, bool) {
	if o == nil || IsNil(o.Counters) {
		return nil, false
	}
	return o.Counters, true
}

// HasCounters returns a boolean if a field has been set.
func (o *InterfaceStats) HasCounters() bool {
	if o != nil && !IsNil(o.Counters) {
		return true
	}

	return false
}

// SetCounters gets a reference to the given InterfaceCounters and assigns it to the Counters field.
func (o *InterfaceStats) SetCounters(v InterfaceCounters) {
	o.Counters = &v
}

// GetQosStats returns the QosStats field value if set, zero value otherwise.
func (o *InterfaceStats) GetQosStats() QoSStats {
	if o == nil || IsNil(o.QosStats) {
		var ret QoSStats
		return ret
	}
	return *o.QosStats
}

// GetQosStatsOk returns a tuple with the QosStats field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InterfaceStats) GetQosStatsOk() (*QoSStats, bool) {
	if o == nil || IsNil(o.QosStats) {
		return nil, false
	}
	return o.QosStats, true
}

// HasQosStats returns a boolean if a field has been set.
func (o *InterfaceStats) HasQosStats() bool {
	if o != nil && !IsNil(o.QosStats) {
		return true
	}

	return false
}

// SetQosStats gets a reference to the given QoSStats and assigns it to the QosStats field.
func (o *InterfaceStats) SetQosStats(v QoSStats) {
	o.QosStats = &v
}

// GetErrorStats returns the ErrorStats field value if set, zero value otherwise.
func (o *InterfaceStats) GetErrorStats() ErrorStats {
	if o == nil || IsNil(o.ErrorStats) {
		var ret ErrorStats
		return ret
	}
	return *o.ErrorStats
}

// GetErrorStatsOk returns a tuple with the ErrorStats field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InterfaceStats) GetErrorStatsOk() (*ErrorStats, bool) {
	if o == nil || IsNil(o.ErrorStats) {
		return nil, false
	}
	return o.ErrorStats, true
}

// HasErrorStats returns a boolean if a field has been set.
func (o *InterfaceStats) HasErrorStats() bool {
	if o != nil && !IsNil(o.ErrorStats) {
		return true
	}

	return false
}

// SetErrorStats gets a reference to the given ErrorStats and assigns it to the ErrorStats field.
func (o *InterfaceStats) SetErrorStats(v ErrorStats) {
	o.ErrorStats = &v
}

// GetOpticalStats returns the OpticalStats field value if set, zero value otherwise.
func (o *InterfaceStats) GetOpticalStats() InterfaceStatsAllOfOpticalStats {
	if o == nil || IsNil(o.OpticalStats) {
		var ret InterfaceStatsAllOfOpticalStats
		return ret
	}
	return *o.OpticalStats
}

// GetOpticalStatsOk returns a tuple with the OpticalStats field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InterfaceStats) GetOpticalStatsOk() (*InterfaceStatsAllOfOpticalStats, bool) {
	if o == nil || IsNil(o.OpticalStats) {
		return nil, false
	}
	return o.OpticalStats, true
}

// HasOpticalStats returns a boolean if a field has been set.
func (o *InterfaceStats) HasOpticalStats() bool {
	if o != nil && !IsNil(o.OpticalStats) {
		return true
	}

	return false
}

// SetOpticalStats gets a reference to the given InterfaceStatsAllOfOpticalStats and assigns it to the OpticalStats field.
func (o *InterfaceStats) SetOpticalStats(v InterfaceStatsAllOfOpticalStats) {
	o.OpticalStats = &v
}

// GetRateStats returns the RateStats field value if set, zero value otherwise.
func (o *InterfaceStats) GetRateStats() InterfaceStatsAllOfRateStats {
	if o == nil || IsNil(o.RateStats) {
		var ret InterfaceStatsAllOfRateStats
		return ret
	}
	return *o.RateStats
}

// GetRateStatsOk returns a tuple with the RateStats field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InterfaceStats) GetRateStatsOk() (*InterfaceStatsAllOfRateStats, bool) {
	if o == nil || IsNil(o.RateStats) {
		return nil, false
	}
	return o.RateStats, true
}

// HasRateStats returns a boolean if a field has been set.
func (o *InterfaceStats) HasRateStats() bool {
	if o != nil && !IsNil(o.RateStats) {
		return true
	}

	return false
}

// SetRateStats gets a reference to the given InterfaceStatsAllOfRateStats and assigns it to the RateStats field.
func (o *InterfaceStats) SetRateStats(v InterfaceStatsAllOfRateStats) {
	o.RateStats = &v
}

func (o InterfaceStats) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InterfaceStats) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["enabled"] = o.Enabled
	if !IsNil(o.Speed) {
		toSerialize["speed"] = o.Speed
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Mtu) {
		toSerialize["mtu"] = o.Mtu
	}
	if !IsNil(o.Mac) {
		toSerialize["mac"] = o.Mac
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.AdminState) {
		toSerialize["adminState"] = o.AdminState
	}
	if !IsNil(o.OperStatus) {
		toSerialize["operStatus"] = o.OperStatus
	}
	if !IsNil(o.AdminStatus) {
		toSerialize["adminStatus"] = o.AdminStatus
	}
	if !IsNil(o.VlanIds) {
		toSerialize["vlanIds"] = o.VlanIds
	}
	if !IsNil(o.LastFlapped) {
		toSerialize["lastFlapped"] = o.LastFlapped
	}
	if !IsNil(o.Counters) {
		toSerialize["counters"] = o.Counters
	}
	if !IsNil(o.QosStats) {
		toSerialize["qosStats"] = o.QosStats
	}
	if !IsNil(o.ErrorStats) {
		toSerialize["errorStats"] = o.ErrorStats
	}
	if !IsNil(o.OpticalStats) {
		toSerialize["opticalStats"] = o.OpticalStats
	}
	if !IsNil(o.RateStats) {
		toSerialize["rateStats"] = o.RateStats
	}
	return toSerialize, nil
}

func (o *InterfaceStats) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"enabled",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInterfaceStats := _InterfaceStats{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInterfaceStats)

	if err != nil {
		return err
	}

	*o = InterfaceStats(varInterfaceStats)

	return err
}

type NullableInterfaceStats struct {
	value *InterfaceStats
	isSet bool
}

func (v NullableInterfaceStats) Get() *InterfaceStats {
	return v.value
}

func (v *NullableInterfaceStats) Set(val *InterfaceStats) {
	v.value = val
	v.isSet = true
}

func (v NullableInterfaceStats) IsSet() bool {
	return v.isSet
}

func (v *NullableInterfaceStats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInterfaceStats(val *InterfaceStats) *NullableInterfaceStats {
	return &NullableInterfaceStats{value: val, isSet: true}
}

func (v NullableInterfaceStats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInterfaceStats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


