/*
H3Net Protocol API

H3Net Protocol schema with various messages and configurations.

API version: 1.0.0
Contact: h3netprotocol@googlegroups.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package h3netclient

import (
	"encoding/json"
)

// checks if the QueryBulkCapabilities200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QueryBulkCapabilities200Response{}

// QueryBulkCapabilities200Response struct for QueryBulkCapabilities200Response
type QueryBulkCapabilities200Response struct {
	Results map[string]CapabilityQueryResponse `json:"results,omitempty"`
}

// NewQueryBulkCapabilities200Response instantiates a new QueryBulkCapabilities200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueryBulkCapabilities200Response() *QueryBulkCapabilities200Response {
	this := QueryBulkCapabilities200Response{}
	return &this
}

// NewQueryBulkCapabilities200ResponseWithDefaults instantiates a new QueryBulkCapabilities200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueryBulkCapabilities200ResponseWithDefaults() *QueryBulkCapabilities200Response {
	this := QueryBulkCapabilities200Response{}
	return &this
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *QueryBulkCapabilities200Response) GetResults() map[string]CapabilityQueryResponse {
	if o == nil || IsNil(o.Results) {
		var ret map[string]CapabilityQueryResponse
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryBulkCapabilities200Response) GetResultsOk() (map[string]CapabilityQueryResponse, bool) {
	if o == nil || IsNil(o.Results) {
		return map[string]CapabilityQueryResponse{}, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *QueryBulkCapabilities200Response) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given map[string]CapabilityQueryResponse and assigns it to the Results field.
func (o *QueryBulkCapabilities200Response) SetResults(v map[string]CapabilityQueryResponse) {
	o.Results = v
}

func (o QueryBulkCapabilities200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QueryBulkCapabilities200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	return toSerialize, nil
}

type NullableQueryBulkCapabilities200Response struct {
	value *QueryBulkCapabilities200Response
	isSet bool
}

func (v NullableQueryBulkCapabilities200Response) Get() *QueryBulkCapabilities200Response {
	return v.value
}

func (v *NullableQueryBulkCapabilities200Response) Set(val *QueryBulkCapabilities200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableQueryBulkCapabilities200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableQueryBulkCapabilities200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueryBulkCapabilities200Response(val *QueryBulkCapabilities200Response) *NullableQueryBulkCapabilities200Response {
	return &NullableQueryBulkCapabilities200Response{value: val, isSet: true}
}

func (v NullableQueryBulkCapabilities200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueryBulkCapabilities200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


