/*
 * H3Net Protocol API
 *
 * H3Net Protocol schema with various messages and configurations.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: h3netprotocol@googlegroups.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AclAllOfStatistics {
    /// Total number of hits across all rules
    #[serde(rename = "totalHits", skip_serializing_if = "Option::is_none")]
    pub total_hits: Option<i32>,
    /// Timestamp of the last statistics update
    #[serde(rename = "lastUpdated", skip_serializing_if = "Option::is_none")]
    pub last_updated: Option<String>,
}

impl AclAllOfStatistics {
    pub fn new() -> AclAllOfStatistics {
        AclAllOfStatistics {
            total_hits: None,
            last_updated: None,
        }
    }
}

