/*
 * H3Net Protocol API
 *
 * H3Net Protocol schema with various messages and configurations.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: h3netprotocol@googlegroups.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BaseMessage {
    /// Message type identifier
    #[serde(rename = "type")]
    pub r#type: String,
    /// ISO 8601 formatted timestamp with timezone
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    /// Schema version
    #[serde(rename = "schemaVersion")]
    pub schema_version: String,
}

impl BaseMessage {
    pub fn new(r#type: String, timestamp: String, schema_version: String) -> BaseMessage {
        BaseMessage {
            r#type,
            timestamp,
            schema_version,
        }
    }
}

