/*
 * H3Net Protocol API
 *
 * H3Net Protocol schema with various messages and configurations.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: h3netprotocol@googlegroups.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BgpNeighborTimers {
    #[serde(rename = "keepalive", skip_serializing_if = "Option::is_none")]
    pub keepalive: Option<i32>,
    #[serde(rename = "holdTime", skip_serializing_if = "Option::is_none")]
    pub hold_time: Option<i32>,
}

impl BgpNeighborTimers {
    pub fn new() -> BgpNeighborTimers {
        BgpNeighborTimers {
            keepalive: None,
            hold_time: None,
        }
    }
}

