/*
 * H3Net Protocol API
 *
 * H3Net Protocol schema with various messages and configurations.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: h3netprotocol@googlegroups.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeviceConfigUpdateMessage {
    #[serde(rename = "type")]
    pub r#type: Type,
    /// ISO 8601 formatted timestamp with timezone
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    /// Schema version
    #[serde(rename = "schemaVersion")]
    pub schema_version: String,
    #[serde(rename = "device")]
    pub device: Box<models::Device>,
    #[serde(rename = "config")]
    pub config: Box<models::DeviceConfigUpdateMessageAllOfConfig>,
    #[serde(rename = "applyImmediately", skip_serializing_if = "Option::is_none")]
    pub apply_immediately: Option<bool>,
}

impl DeviceConfigUpdateMessage {
    pub fn new(r#type: Type, timestamp: String, schema_version: String, device: models::Device, config: models::DeviceConfigUpdateMessageAllOfConfig) -> DeviceConfigUpdateMessage {
        DeviceConfigUpdateMessage {
            r#type,
            timestamp,
            schema_version,
            device: Box::new(device),
            config: Box::new(config),
            apply_immediately: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "DEVICE_CONFIG_UPDATE")]
    DeviceConfigUpdate,
}

impl Default for Type {
    fn default() -> Type {
        Self::DeviceConfigUpdate
    }
}

