/*
 * H3Net Protocol API
 *
 * H3Net Protocol schema with various messages and configurations.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: h3netprotocol@googlegroups.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeviceInfoResponse {
    /// Must be DEVICE_INFO_RESPONSE
    #[serde(rename = "type")]
    pub r#type: Type,
    /// ISO 8601 formatted timestamp with timezone
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    /// Schema version
    #[serde(rename = "schemaVersion")]
    pub schema_version: String,
    #[serde(rename = "deviceId")]
    pub device_id: String,
    #[serde(rename = "settings")]
    pub settings: Box<models::DeviceSettings>,
}

impl DeviceInfoResponse {
    pub fn new(r#type: Type, timestamp: String, schema_version: String, device_id: String, settings: models::DeviceSettings) -> DeviceInfoResponse {
        DeviceInfoResponse {
            r#type,
            timestamp,
            schema_version,
            device_id,
            settings: Box::new(settings),
        }
    }
}
/// Must be DEVICE_INFO_RESPONSE
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "DEVICE_INFO_RESPONSE")]
    DeviceInfoResponse,
}

impl Default for Type {
    fn default() -> Type {
        Self::DeviceInfoResponse
    }
}

