/*
 * H3Net Protocol API
 *
 * H3Net Protocol schema with various messages and configurations.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: h3netprotocol@googlegroups.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryBulkCapabilities200Response {
    #[serde(rename = "results", skip_serializing_if = "Option::is_none")]
    pub results: Option<std::collections::HashMap<String, models::CapabilityQueryResponse>>,
}

impl QueryBulkCapabilities200Response {
    pub fn new() -> QueryBulkCapabilities200Response {
        QueryBulkCapabilities200Response {
            results: None,
        }
    }
}

