/*
 * H3Net Protocol API
 *
 * H3Net Protocol schema with various messages and configurations.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: h3netprotocol@googlegroups.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValidateRoutingConfig200ResponseErrorsInner {
    #[serde(rename = "path", skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl ValidateRoutingConfig200ResponseErrorsInner {
    pub fn new() -> ValidateRoutingConfig200ResponseErrorsInner {
        ValidateRoutingConfig200ResponseErrorsInner {
            path: None,
            message: None,
        }
    }
}

